name: build-unsigned-ipa

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Archive (unsigned)
        run: |
          set -e
          xcodebuild -scheme BoxAutomation -configuration Release -destination "generic/platform=iOS" -archivePath build/BoxAutomation.xcarchive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" archive

      - name: Package .ipa (manual)
        run: |
          set -e
          APP_PATH=$(find build/BoxAutomation.xcarchive/Products/Applications -maxdepth 1 -name "*.app" | head -n 1)
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          cd Payload
          /usr/bin/zip -r ../BoxAutomation-unsigned.ipa .
          cd ..
          shasum -a 256 BoxAutomation-unsigned.ipa > BoxAutomation-unsigned.ipa.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BoxAutomation-unsigned
          path: |
            BoxAutomation-unsigned.ipa
            BoxAutomation-unsigned.ipa.sha256